### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by davetang** [DaehwanKimLab/hisat-genotype#27]
Hi Chris,

thank you for quickly addressing the [UnboundLocalError](https://github.com/DaehwanKimLab/hisat-genotype/issues/26); I pulled the updated code and re-ran HISAT-genotype as before but now I'm getting another error.

Below is from the log.

```
> Base and Files:hla NA12892.extracted.1.fq.gz-hla-extracted-1.fq.gz NA12892.extracted.1.fq.gz-hla-extracted-2.fq.gz
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dtang/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/dtang/tool/hisat-genotype-20bce67141836ff9cc6b0686340c2a2b678cde75/hisatgenotype_modules/hisatgenotype_typing_core.py", line 2687, in genotyping_locus
    dbversion)
  File "/home/dtang/tool/hisat-genotype-20bce67141836ff9cc6b0686340c2a2b678cde75/hisatgenotype_modules/hisatgenotype_typing_core.py", line 1539, in typing
    simulation)])
  File "/home/dtang/tool/hisat-genotype-20bce67141836ff9cc6b0686340c2a2b678cde75/hisatgenotype_modules/hisatgenotype_assembly_graph.py", line 197, in __init__
    assert len(seq) == len(var)
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dtang/tool/hisat-genotype-20bce67141836ff9cc6b0686340c2a2b678cde75/hisatgenotype", line 673, in typing_process
    ofnlog.write(str(x.get()))
  File "/home/dtang/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError
```

Thanks,
Dave

**Comment by chbe-helix** [comment]
Hi Dave,

That's an interesting unexpected error. Let me look into it and run a trace on the error to find the source. Until then I might suggest running it without --assembly option for now. That should allow you to genotype A,B,C,DPA1,DPB1,DQA1,DQB1, and DRB1 quickly and reliably. Will you need the assembly before the next release of HISATgenotpye in Nov/Dec?

Thanks,
Chris

**Comment by davetang** [comment]
Hi Chris,

I can wait for the next release for the assembly mode. Thank you for following up!

Thanks,
Dave

**Comment by davetang** [comment]
Hi Chris,

I was just wondering whether there has been any development regarding the assembly mode?

Thank you!
Dave

**Comment by chbe-helix** [comment]
Hi Dave,

So sorry for the inconvenience and for my delay in getting the assembly working. I have not had a chance to address this specific issue yet. I am hoping to get this fixed by the end of Q1 2021. Again, I profusely apologize for the delay.

Thanks,
Chris

**Comment by davetang** [comment]
Hi Chris,

no worries at all! I was just curious on the status.

Take care,
Dave

**Comment by zhqingit** [comment]
Hi Chris,

I got the same error. Just wondering if you got chance to solve it? thank you!

Best,
Qing
