### ISSUE TITLE
Error when converting .report into csv (hisatgenotype_toolkit)

### ISSUE THREAD

**Issue by Tijs-dot** [DaehwanKimLab/hisat-genotype#40]
Hi Chris,
I have tried using HISAT-genotype with some fastq files and it runs fine. Now I tried to use the HISAT-genotype toolkit to convert my output into csv format. This gave following error:

$ hisatgenotype_toolkit parse-results -t 2 --csv --in-dir hisatgenotype_resultP2B1L8allele, _, percent = line.split()^C
(hsgtenv) [twatzeels@riro app]$ cd hisatgenotype
(hsgtenv) [twatzeels@riro hisatgenotype]$ hisatgenotype_toolkit parse-results -t 2 --csv --in-dir hisatgenotype_resultP2B1L8
Traceback (most recent call last):
  File "/home/MOLGEN/twatzeels/app/hisatgenotype/hisatgenotype_tools/hisatgenotype_parse_results.py", line 160, in <module>
    result_process(args)
  File "/home/MOLGEN/twatzeels/app/hisatgenotype/hisatgenotype_tools/hisatgenotype_parse_results.py", line 69, in result_process
    report_results[report] = typing_common.call_nuance_results(report)
  File "/home/MOLGEN/twatzeels/app/hisatgenotype/hisatgenotype_modules/hisatgenotype_typing_common.py", line 2021, in call_nuance_results
    allele, _, percent = line.split()
ValueError: too many values to unpack (expected 3)
Script exited with error 1

I also tried this command using the files provided by the HISAT tutorial, and this worked fine. I think there is something wrong with the report files I generated with HISAT-genotype.
Can you help me with this?

Kind regards,
Tijs

**Comment by chbe-helix** [comment]
Hi Tijs,

Absolutely! I think the easiest way to find the offending file is to:
1) Locate the hisatgenotype_typing_common.py file in the hisatgenotype_modules/ folder of HISAT-genotype (where ever you installed it
2) Open the hisatgenotype_typing_common.py file in the editor of your choice
3) Go to line 2021 at the bottom of the file. This is the code that is producing the error
4) Right above the `allele, _, percent = line.split()` code add the following:
```
print(line, nfile)
```
5) Save the file
6) Rerun the script

This will produce a lot of lines but it will show you the formatting error and the file where the error is. Hope this helps!

Thanks,
Chris

**Comment by Tijs-dot** [comment]
Hi Chris,

I tried doing what you explained above, but the error remained unchanged, so that meant it failed even before the first real output line. 
So I tried making some changes in the lines above, and it turns that the parameter --keep-low-abundancy-alleles caused the program to fail. 
If I change or remove the word "abundance" from this command line, the program runs fine!

Tijs

**Comment by chbe-helix** [comment]
Hi Tijs,

That's an unexpected issue. I'll add this to my list of bugs to examine to see if there is something I missed when designing the script. Thanks for the update!

Thanks,
Chris

**Comment by Tijs-dot** [comment]
Hi Chris,

I was wondering if there is a way to trim the fields distinguishing between different HLA calls for the same allele, for the abundance values when using the -t option from hisatgenotype_toolkit. I wanted to convert the .report output from HISAT-genotype into a csv format, while trimming the last two fields, so I would be able to group all alleles. However, this only seems to trim the allele count fields, not the ones in the abundance part of the report output.

4392 reads and 2212 pairs are aligned

1 A*02:01:01:01 (count: 1550)
2 A*02:01:01:05 (count: 1550)
3 A*02:01:01:06 (count: 1550)
4 A*02:01:01:07 (count: 1550)
5 A*02:01:01:08 (count: 1548)
6 A*02:01:126 (count: 1530)
7 A*02:648 (count: 1525)
8 A*02:30:01 (count: 1523)
9 A*02:562 (count: 1523)
10 A*02:498 (count: 1518)

1 ranked A*01:01:01:01 (abundance: 30.96%)
2 ranked A*02:01:01:01 (abundance: 17.26%)
3 ranked A*02:01:01:05 (abundance: 17.26%)
4 ranked A*02:01:01:06 (abundance: 17.26%)
5 ranked A*02:01:01:07 (abundance: 17.26%)

Does this question make sense to you? I don't know if you would like me to contact you via a new github issue, or if this email is fine. I was not sure if this question would be useful as a thread on the HISAT-genotype github page.

Thanks in advance,
Tijs
________________________________
Van: Chris Bennett <notifications@github.com>
Verzonden: maandag 11 januari 2021 08:49
Aan: DaehwanKimLab/hisat-genotype <hisat-genotype@noreply.github.com>
CC: Tijs Watzeels <Tijs.Watzeels@student.uantwerpen.be>; Author <author@noreply.github.com>
Onderwerp: Re: [DaehwanKimLab/hisat-genotype] Error when converting .report into csv (hisatgenotype_toolkit) (#40)


Hi Tijs,

That's an unexpected issue. I'll add this to my list of bugs to examine to see if there is something I missed when designing the script. Thanks for the update!

Thanks,
Chris
