### ISSUE TITLE
ValueError: not enough values to unpack (expected 11, got 3)

### ISSUE THREAD

**Issue by salonso65** [DaehwanKimLab/hisat-genotype#46]
Hi Chris
I have been failing to get hisatgenotype working, and after a week of missery I have decided to knock at your door for help. Here is my problem:

I have installed:
hisatgenotype version 1.3.2
HISAT2 version 2.2.1 
python Python 3.7.1 
and RHEL 7.2

My command is:

hisatgenotype  --base hla --locus-list A -1 ILMN/NA12892.extracted.1.fq.gz -2 ILMN/NA12892.extracted.2.fq.gz

Result (1):

No /MSA03/hisat-genotype/indicies/hla.snp file found (My comment: well, in fact there is one hla.out but empty)
Building hla Database
Except exception err_msg =  multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/MSA03/hisat-genotype/hisatgenotype_modules/hisatgenotype_typing_core.py", line 2408, in genotyping_locus
    verbose >= 1)
  File "/MSA03/hisat-genotype/hisatgenotype_modules/hisatgenotype_typing_common.py", line 54, in wrapper
    func(*args, **kwargs)
  File "/MSA03/hisat-genotype/hisatgenotype_modules/hisatgenotype_typing_common.py", line 568, in extract_database_if_not_exists
    verbose)
  File "/MSA03/hisat-genotype/hisatgenotype_modules/hisatgenotype_typing_process.py", line 390, in extract_vars
    temp_allele_id, flag, chr, left, _, cigar_str = cols[:6]
ValueError: not enough values to unpack (expected 6, got 3)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/MSA03/hisat-genotype/hisatgenotype", line 738, in typing_process
    ofnlog.write(str(x.get()))
  File "/opt/conda/miniconda3/lib/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
ValueError: not enough values to unpack (expected 6, got 3)

If I now run it a second time (result-2):

        1: Extracting reads from NA12892.extracted.1.fq.gz

Traceback (most recent call last):
  File "/MSA03/hisat-genotype/hisatgenotype", line 845, in <module>
    typing_process(args)
  File "/MSA03/hisat-genotype/hisatgenotype", line 553, in typing_process
    args.verbose)
  File "/MSA03/hisat-genotype/hisatgenotype_modules/hisatgenotype_typing_process.py", line 1776, in extract_reads
    verbose)
  File "/MSA03/hisat-genotype/hisatgenotype_modules/hisatgenotype_typing_process.py", line 1615, in work
    read_name, flag, chr, pos, mapQ, cigar, _, _, _, read, qual = cols[:11]
ValueError: not enough values to unpack (expected 11, got 3)

(if it helps I have:
line:  HISAT2@HD        VN:1.0  SO:unsorted
cols:  ['HISAT2@HD', 'VN:1.0', 'SO:unsorted'])

Any help welcome! Thanks!

**Comment by chbe-helix** [comment]
Hi Salonso,

Thanks for reaching out! It looks like there is an error in the database building for HLA. There is likely an incomplete database built in your hisat-genotype source directory as HISAT-genotype will not delete indices that fail to build properly.

I'd look in there for an indices folder and look at deleting any incomplete files. Alternatively, you can try rebuilding hisat-genotype manually according to the manual online. Let me know if this helps!

Thanks,
Chris

**Comment by salonso65** [comment]
Seems to be working now. I think tehproblem was a previous hisat2 install that was interfering.
Thanks.
