### ISSUE TITLE
Cannot run hisat-genotype for BAM file 

### ISSUE THREAD

**Issue by nikyk** [DaehwanKimLab/hisat-genotype#50]
run command:
hisatgenotype --base hla --threads 4  --bamfile SRRxxxxxx.bam
BAM file is generated previously by STAR 2.7.0
--------------------Python error trace message:
Traceback (most recent call last):
  File "/home/Common/HISAT2/hisat-genotype/hisatgenotype", line 763, in <module>
    typing_process(args)
  File "/home/Common/HISAT2/hisat-genotype/hisatgenotype", line 539, in typing_process
    assert fq_fname_base
AssertionError
----------------------------------------------------------
Additional info:
BAM file is found by hisatgenotype script, *.bai index file is successfully built

Questions:
1) Is there some way to run HG for bam files?
2) If yes, is it worth using BAM instead of fq.gz? Is there a benefit?

**Comment by chbe-helix** [comment]
Hi Nikyk,

HISATgenotype can use bam files though it is not optimized for it and there may be some unknown bugs. Furthermore, HISATgenotype can not use BAM files aligned to standard GRCh37 or GRCh38 human references. We have designed HISATgenotype to use a custom genotype genome that is optimized for genotyping but has shifted coordinates to any reference. We recommend running HISATgenotype with fastq files for optimal results. Hope this helps!

Thanks,
Chris

**Comment by nikyk** [comment]
Ok, thanks. It would be fruitful to add this note to Manual, where --bamfile option is described

**Comment by chbe-helix** [comment]
I'll add that to the list of changes. Thanks!

Thanks,
Chris

**Comment by nikyk** [comment]
Feature request:
Add descriptive error message in case when input bam isn't aligned to compatible reference.

**Comment by thomasKuilman** [comment]
I have been trying to run hisatgenotype on an existing bam-file that was created using hisatgenotype (i.e., with the correct reference) but still I get the same issue as reported above:

```
$ hisatgenotype --base hla --out-dir $OUT_DIR --bamfile $PATH_TO_BAM --index_dir $PATH_TO_INDICIES

Traceback (most recent call last):
  File "/home/thomaskuilman/Neogene_Dropbox/Thomas/tmp/hisatgenotype/hisatgenotype", line 771, in <module>
    typing_process(args)
  File "/home/thomaskuilman/Neogene_Dropbox/Thomas/tmp/hisatgenotype/hisatgenotype", line 539, in typing_process
    assert fq_fname_base
AssertionError
```

Could you please check whether this is a valid call to hisatgenotype and / or whether there are any issues with HLA-typing from an existing bam-file?
