### ISSUE TITLE
Problem with installlation 

### ISSUE THREAD

**Issue by nebilaj** [DaehwanKimLab/hisat-genotype#57]
Hello, 
I am having troubles installing hisat-genotype , this appears when I try to install it manually , :
`I n file included from hisat2_build.cpp:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/iostream:37:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/ios:215:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__locale:14:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:506:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string_view:175:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__string:57:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/algorithm:640:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:418:
./version:1:1: error: expected unqualified-id
2.2.1`

And When I tried to install it automatically, (following the manual) only hisat2 command worked and hisatgenotype command was ' not found'. 
Can anyone help me?
Thank in advance

**Comment by chbe-helix** [comment]
Hi nebilaj,

I'm sorry to see there are issues trying to dow load hisat-genotype. Could you confirm for me that hisat-genotype repo was downloaded and that hisat2 is running properly?

You should be able to run ```hisat2 --help``` in your terminal to make sure it is running.


Thanks,
Chris

**Comment by nebilaj** [comment]
Hello Chris 
Thank you for your quick answer, I've been trying to make this work for a week , 
Hisat2 is only working when I donwload hit with conda , but it does not have hisatgenotype with it. 
I tried again now to donwload from scratch hisat-genotyme with this command : 
`git clone https://github.com/DaehwanKimLab/hisat-genotype.git ~/hisatgenotype
cd hisatgenotype
bash setup.sh -r` 



but it did not work as I got this answer :  `atal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [hisat2-build-s] Error 1
Adding to /Users/nebila/.bash_profile and sourcing
setup.sh: line 117: wget: command not found
tar: Error opening archive: Failed to open 'genotype_genome_20180128.tar.gz'
rm: cannot remove 'genotype_genome_20180128.tar.gz': No such file or directory
setup.sh: line 122: wget: command not found
tar: Error opening archive: Failed to open 'grch38.tar.gz'
rm: cannot remove 'grch38.tar.gz': No such file or directory
/Users/nebila/hisatgenotype/hisat2/hisat2-inspect:24: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/nebila/hisatgenotype/hisat2/hisat2-inspect", line 73, in <module>
    main()
  File "/Users/nebila/hisatgenotype/hisat2/hisat2-inspect", line 69, in main
    os.execv(inspect_bin_spec, arguments)        
FileNotFoundError: [Errno 2] No such file or directory
[faidx] Could not build fai index genome.fa.fai
Cloning into 'hisatgenotype_db'...
remote: Enumerating objects: 750, done.
remote: Total 750 (delta 0), reused 0 (delta 0), pack-reused 750
Receiving objects: 100% (750/750), 31.27 MiB | 8.34 MiB/s, done.
Resolving deltas: 100% (214/214), done.
/Users/nebila/hisatgenotype
(base) nebila@x86_64-apple-darwin13 hisatgenotype % hisat2
zsh: command not found: hisat2
(base) nebila@x86_64-apple-darwin13 hisatgenotype % 
`

**Comment by nebilaj** [comment]
So I've tried once again to  install hisat2 in a conda environment running on python 3.7.
Hisat2 is working but then when I try to install hisat-genotype using this command lines : 

`git clone https://github.com/DaehwanKimLab/hisat-genotype.git ~/hisatgenotype
cd hisatgenotype
bash setup.sh -r`

 I have this message error when trying to run the command :  hisatgenotype --help :

 `(python37) nebilajj@dyn903-220 ~ % hisatgenotype
zsh: command not found: hisatgenotype
(python37) nebilajj@dyn903-220 ~ % `

**Comment by chbe-helix** [comment]
Hi nebilaj,

I think we know what the issue is. Please run the following code and see if it works:
```
git clone --recurse-submodules https://github.com/DaehwanKimLab/hisat-genotype ~/hisatgenotype
cd ~/hisatgenotype/hisat2

git checkout dev
make

cd ../

echo "export PATH=~/hisatgenotype:~/hisatgenotype/hisat2:$PATH" >> .bashrc
echo "export PYTHONPATH=~/hisatgenotype/hisatgenotype_modules:$PYTHONPATH" >> .bashrc
```

Make sure you change any paths or directories to fit your setup. Let me know if this corrects your issue!

Thanks,
Chris

**Comment by nebilaj** [comment]
Hi chris, 
Unfortunately, it still doesn't work :/ , I have this kind of message when I try to compile with make : 
`third_party/cpuid.h:138:14: warning: value size does not match register size specified by the constraint and modifier [-Wasm-operand-widths]
           : "=&r" (__eax), "=&r" (__ebx)
                    ^
third_party/cpuid.h:132:22: note: use constraint modifier "w"
           "xor{l}\t{%2, %0|%0, %2}\n\t"
                            ^~
                            %w0
`

and at the end this : `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__config:1035:48: note: expanded from macro '_LIBCPP_DEPRECATED'
#    define _LIBCPP_DEPRECATED __attribute__ ((deprecated))
                                               ^
11 warnings and 2 errors generated.
make: *** [hisat2-build-s] Error 1`


so when I type hisatgenotype --help it still says 

`zsh: command not found: hisatgenotype`

, Nebila

**Comment by nebilaj** [comment]
I tried to delete both hisat2 ( because I have also one running in my conda environment that I downloaded directly from anaconda with this line 'conda install -c bioconda hisat2'  ) 
and when I tried to follow your step do download again hisat-genotype I can't even make hisat2 working

**Comment by chbe-helix** [comment]
Hi Nebila,

I think this falls into a hisat2 issue so I'm going to get you in touch with our HISAT2 team to help you with your troubles. My suggestion is to work with them to get HISAT2 in your system then head back here and I can help you get hisat-genotype working with that instillation

Thanks,
Chris
