### ISSUE TITLE
Typing results failing for genes other than 1A1, 2A6, 3A4 when calling "hisatgenotype --base cyp"

### ISSUE THREAD

**Issue by dcolomb1** [DaehwanKimLab/hisat-genotype#63]
Hello,
Congrats on this software. I had a few issues but I now found out the issue with DRB3-4-5 is known and been also reported here #25.
I also have another issue with the CYP genes.
```
> Base and Files:cyp NG-26027_A3577_188_886001006_lib432668_7055_1_1.fastq.gz-cyp-extracted-1.fq.gz NG-26027_A3577_188_886001006_lib432668_7055_1_1.fastq.gz-cyp-extracted-2.fq.gz
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/domino/datasets/local/HISAT2/hisatgenotypeMan/hisatgenotype_modules/hisatgenotype_typing_core.py", line 2655, in genotyping_locus
    typing(simulation,
  File "/domino/datasets/local/HISAT2/hisatgenotypeMan/hisatgenotype_modules/hisatgenotype_typing_core.py", line 1787, in typing
    Gene_prob = [[Gene_cmpt.keys()[0], 1.0]]
TypeError: 'dict_keys' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/domino/datasets/local/HISAT2/hisatgenotypeMan/hisatgenotype", line 675, in typing_process
    ofnlog.write(str(x.get()))
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'dict_keys' object is not subscriptable

```
I am running the latest software with all required specs on a Open Data Lab workspace.

Thanks and best,
Daniele

**Comment by dfcolombo** [comment]
`close #63`
