### ISSUE TITLE
Python 3 and issue with indexing

### ISSUE THREAD

**Issue by dcolomb1** [DaehwanKimLab/hisat-genotype#65]
Hello,
I am observing the following dictionary ordering issue in the log. Any ideas whether it might affect results? I am using Python 3.8.5.
Kind regards,

`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/domino/datasets/local/HISAT2/hisatgenotypeMan/hisatgenotype_modules/hisatgenotype_typing_core.py", line 2655, in genotyping_locus
    typing(simulation,
  File "/domino/datasets/local/HISAT2/hisatgenotypeMan/hisatgenotype_modules/hisatgenotype_typing_core.py", line 1787, in typing
    Gene_prob = [[Gene_cmpt.keys()[0], 1.0]]
TypeError: 'dict_keys' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/domino/datasets/local/HISAT2/hisatgenotypeMan/hisatgenotype", line 675, in typing_process
    ofnlog.write(str(x.get()))
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: 'dict_keys' object is not subscriptable
`

**Comment by phlimu** [comment]
Hey,
I don't know if it was the exact same error but we got it running by using python version 3.6.8 and hisat2 version 2.2.1.
Maybe that helps.
