### ISSUE TITLE
Building a Graph Reference and Index

### ISSUE THREAD

**Issue by jhylwq123** [DaehwanKimLab/hisat-genotype#69]
I'm a little confused about the Graph Reference panel. I guess it's a stupid question to ask but how many samples in the  Reference panel? There are so many files in indicies folder and Is there any tutorials for building a graph reference?

**Comment by Yunuuuu** [comment]
The same problem, I cannot find a [Tutorial](https://daehwankimlab.github.io/hisat-genotype/tutorials/)  to build a graph reference

**Comment by Yunuuuu** [comment]
The command help page also lacks enouph message to run the command
```
❯ hisatgenotype_toolkit build-genome --help
usage: hisatgenotype_build_genome.py [-h] [--base BASE_FNAME] [--locus-list LOCUS_LIST] [--inter-gap INTER_GAP] [--intra-gap INTRA_GAP] [--aligner ALIGNER] [--linear-index] [--commonvar] [--clinvar]
                                     [-p THREADS] [-v]

Build genotype genome

options:
  -h, --help            show this help message and exit
  --base BASE_FNAME, --base-fname BASE_FNAME
                        Base file name for index, variants, haplotypes, etc. (e.g. hla, rbg, codis) (default: empty)
  --locus-list LOCUS_LIST
                        A comma-separated list of gene names (default: empty, all genes)
  --inter-gap INTER_GAP
                        Maximum distance for variants to be in the same haplotype
  --intra-gap INTRA_GAP
                        Break a haplotype into several haplotypes
  --aligner ALIGNER     Set aligner to use (ex. hisat2, bowtie2) (default: hisat2)
  --linear-index        Use linear index
  --commonvar           Include common variants from dbSNP
  --clinvar             Include variants from ClinVar database
  -p THREADS, --threads THREADS
                        Number of threads
  -v                    Print statistics to stderr
```

```
❯ hisatgenotype_toolkit build-genome -v
Traceback (most recent call last):
  File "/home/pengyun/hisatgenotype/hisatgenotype_tools/hisatgenotype_build_genome.py", line 546, in <module>
    typing_common.clone_hisatgenotype_database()
  File "/home/pengyun/hisatgenotype/hisatgenotype_modules/hisatgenotype_typing_common.py", line 52, in wrapper
    func(*args, **kwargs)
TypeError: clone_hisatgenotype_database() missing 1 required positional argument: 'destination'
Script exited with error 1
```
